spring.application.name: content-service

spring:
  profiles:
    active: dev
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://167.172.78.79:8888

logging:
  level:
    org:
      springframework:
        #        web: DEBUG
        #        mail: DEBUG
        security: DEBUG




